apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskappdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworldflask
  template:
    metadata:
      labels:
        app: helloworldflask
    spec:
      containers:
      - name: helloworldflask
        image: 192.168.2.54:5000/hello-world-flask:latest
        ports:
          containerPort: 5134
      imagePullSecrets:
        - name: privateregistrycredential

---
apiVersion: v1
kind: Service
metadata:
  name: flaskappservice
spec:
  selector:
    app: flaskappdeployment
  ports:
  - port: 6000
    targetPort: 5134
  type: LoadBalancer
