apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldflask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworldflask
  template:
    metadata:
      labels:
        app: helloworldflask
    spec:
      containers:
      - name: helloworldflask
        image: 192.168.2.54:5000/hello-world-flask:latest
        ports:
        - containerPort: 5134
      imagePullSecrets:
        - name: privateregistrycredential

---
apiVersion: v1
kind: Service
metadata:
  name: helloworldflask
spec:
  type: NodePort
  selector:
    app: helloworldflask
  ports:
  - protocol: TCP
    port: 5134
    targetPort: 5134
